version: '3'

volumes:
  frontend_data:
    driver: local
    driver_opts:
      type: none
      device: /home/eryilmaz/data/frontend
      o: bind
  postgresql_data:
    driver: local
    driver_opts:
      type: none
      device: /home/eryilmaz/data/postgresql
      o: bind

networks:
  network:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - frontend_data:/var/www/html
    restart: always
    networks:
      - network
    depends_on:
      - adminer
  postgresql:
    container_name: postgresql 
    build: ./requirements/postgresql
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - network
    restart: always
    env_file:
      - .env
  
  adminer:
    container_name: adminer
    build: ./requirements/adminer
    restart: always
    expose:
     - "9000"
    networks:
      - network
  
  # redis:
  #   container_name: redis
  #   build: ./requirements/redis
  #   ports:
  #    - '6379:6379'
  #   restart: always
  #   env_file:
  #     - .env
  #   volumes:
  #     - frontend:/var/www/html
  #   networks:
  #     - network