version: '3'

volumes:
  postgresql_data:
    driver: local
    driver_opts:
      type: none
      device: /home/eryilmaz/data/postgresql
      o: bind

networks:
  network:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network
    depends_on:
      - adminer
      - wordpress

  postgresql:
    container_name: postgresql 
    build: ./requirements/postgresql
    volumes:
      - postgresql:/var/lib/postgresql
    networks:
      - network
    restart: always
    env_file:
      - .env
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: always
    depends_on:
      - mariadb
    expose:
     - "9000"
    networks:
      - network
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
     - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network